---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
# read tables
abun <- readRDS("../data/R/counts_resfinder_reads.rds")
meta <- readRDS("../data/R/metadata_samples_reads.rds")

meta <- meta %>% arrange(Surface, Tecnology, Country)
abun <- abun[rownames(meta), ]
```

```{r}
# Create tibble with the total amount of AMR counts across the samples with the metadata
df_TotCounts <- tibble(
  sample = rownames(abun),
  TotCounts = rowSums(abun)
) %>%
  left_join(rownames_to_column(meta,"sample"), by = "sample")
```

```{r}
# Check the total amount of AMR counts for the two different tecnology
df_TotCounts %>%
  reframe(TotCounts = sum(TotCounts),
          TotReads = sum(Reads_count), .by = Tecnology) %>%
  mutate(log10_Ratio = log10(TotCounts / TotReads))
```


```{r}
# Compare the ratio of the total amount of AMR respect sample reads number
df_TotCounts %>%
  mutate(AMR_ratio = TotCounts / Reads_count,
         AMR_presence = case_when(
           TotCounts == 0 ~ "missing",
           TotCounts <= 100 ~ "<= 100",
           TotCounts > 100 ~ ">  100"
         )) %>%
  ggplot(aes(x = Time, y = AMR_ratio, color = Tecnology, shape = AMR_presence)) +
  geom_point(size = 2) +
  facet_wrap(~ Country + Surface, nrow = 2, scales = "free") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = c(.925, .25)) +
  scale_y_continuous(labels = scales::scientific)
```

Two samples in carcass are without AMR counts...


```{r}
library(pheatmap)
df_rows <- data.frame(meta %>% unite("Surface-Tecnology", c(Surface, Tecnology), sep = " - ") %>% select(`Surface-Tecnology`))

pheatmap(log10(abun[meta$Surface!="carcass",]+1), cluster_rows = FALSE,
         show_colnames = FALSE, show_rownames = FALSE,
         annotation_row = df_rows)
```

