---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
# read tables
abun <- as.data.frame(readRDS("../data/R/counts_resfinder_reads.rds")) %>%
  bind_rows(
    as.data.frame(readRDS("../data/R/counts_resfinder_contigs_illumina_nomobile.rds"))
    ) %>%
  replace(is.na(.), 0)
meta <- readRDS("../data/R/metadata_samples_reads.rds") %>%
  bind_rows(readRDS("../data/R/metadata_samples_contigs_illumina_nomobile.rds"))

meta <- meta %>% arrange(Surface, Tecnology, Country)
abun <- abun[rownames(meta), ]

abun <- abun[meta$Surface != "carcass", ]
meta <- meta[meta$Surface != "carcass", ]

# get relative abundances
rela <- abun / rowSums(abun)
```

```{r, fig.width=9, fig.height=5}
df_stats <- abun %>%
  as_tibble(rownames = "sample") %>%
  left_join(meta %>% rownames_to_column("sample") %>% 
              select(sample, Tecnology, Surface, Level), by = "sample") %>%
  filter(Surface != "carcass") %>%
  pivot_longer(-c(sample, Tecnology, Surface, Level), 
               names_to = "AMR", values_to = "count") %>%
  reframe(
    detection = sum(count>0),
    prevalence = sum(count>0) / n(),
    median = if_else(any(count!=0), median(count), 0),
    mean = if_else(any(count!=0), mean(count), 0),
    sumCount = sum(count),
    .by = c(AMR, Tecnology, Surface, Level)
  ) %>%
  pivot_longer(cols = c(detection, prevalence, median, mean, sumCount), names_to = "stat", 
               values_to = "value") 
```

```{r, fig.height=12, fig.width=9}
df_stats %>%
  unite("TecnologyLevel", c(Tecnology, Level), sep = "_", remove = FALSE) %>%
  filter(stat %in% c("detection","scaledSumCount")) %>%
  ggplot(aes(x = value, fill = TecnologyLevel)) +
  geom_histogram(bins = 10, alpha = .5, color = "gray", position = "dodge") +
  #scale_x_log10() +
  facet_wrap(~ Surface + stat, scales = "free", ncol = 2) +
  theme_bw() +
  theme(legend.position = "top")
```

```{r}
AMR_pass <- rela %>%
  as_tibble(rownames = "sample") %>%
  left_join(meta %>% rownames_to_column("sample") %>% 
              select(sample, Tecnology, Country, Surface), by = "sample") %>%
  pivot_longer(-c(sample, Tecnology, Country, Surface), names_to = "AMR", values_to = "count") %>%
  reframe(
    detection = sum(count>0),
    .by = c(AMR,Tecnology, Surface, Country)
  ) %>% 
  mutate(passed = detection >= 3) %>%
  reframe(AMR_passed = unique(AMR[passed])) %>%
  pull(AMR_passed)
```

```{r}
abun_filt <- abun[, AMR_pass]
```

```{r}
tibble(
  sample = rownames(abun),
  perc_count_conserved = rowSums(abun_filt) / rowSums(abun)
) %>%
  left_join(rownames_to_column(meta, "sample"), by = "sample") %>%
  ggplot(aes(x = perc_count_conserved, fill = Tecnology)) +
  geom_histogram(bins = 10, alpha = .75, color = "lightgray", position = "dodge") +
  theme_bw()
```

```{r}
abun_filt_CLR <- abun_filt %>% 
  zCompositions::cmultRepl() %>%
  vegan::decostand(method = "clr", MARGIN = 1)
```


