---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
```

```{r}
bac_reads <- readRDS("../data/R/bac_reads.rds") 
arg_reads <- readRDS("../data/R/arg_reads.rds")
arg_contigs <- readRDS("../data/R/arg_contigs.rds")
```

```{r}
bac_reads_sp <- bac_reads_sp %>%
  mutate(highlight = any(rela >= .05), .by = "species_taxizedb")

bac_reads_gen <- bac_reads_sp %>%
  group_by(sample_id, genus, Surface) %>%
  summarise(rela = sum(rela), .groups = "drop") %>%
  mutate(highlight = any(rela >= .05), .by = genus)

bac_reads_fam <- bac_reads_sp %>%
  group_by(sample_id, family, Surface) %>%
  summarise(rela = sum(rela), .groups = "drop") %>%
  mutate(highlight = any(rela >= .05), .by = family)

bac_reads_phy <- bac_reads_sp %>%
  group_by(sample_id, phylum, Surface) %>%
  summarise(rela = sum(rela), .groups = "drop") %>%
  mutate(highlight = any(rela >= .05), .by = phylum) 
```

```{r}
arg_contigs_sp <- arg_contigs %>%
  #filter(species_diamond != "Unknown") %>%
  group_by(sample_id, species_diamond, Surface) %>%
  summarise(abun = sum(abun), .groups = "drop") %>%
  mutate(rela = abun / sum(abun), .by = "sample_id") %>%
  mutate(highlight = any(rela >= .005), .by = species_diamond)

arg_contigs_gen <- arg_contigs %>%
  group_by(sample_id, genus_diamond, Surface) %>%
  summarise(abun = sum(abun), .groups = "drop") %>%
  mutate(rela = abun / sum(abun), .by = "sample_id") %>%
  mutate(highlight = any(rela >= .05), .by = genus_diamond)
    
arg_contigs_fam <- arg_contigs %>%
  group_by(sample_id, family_diamond, Surface) %>%
  summarise(abun = sum(abun), .groups = "drop") %>%
  mutate(rela = abun / sum(abun), .by = "sample_id") %>%
  mutate(highlight = any(rela >= .05), .by = family_diamond)

arg_contigs_phy <- arg_contigs %>%
  group_by(sample_id, phylum_diamond, Surface) %>%
  summarise(abun = sum(abun), .groups = "drop") %>%
  mutate(rela = abun / sum(abun), .by = "sample_id") %>%
  mutate(highlight = any(rela >= .05), .by = phylum_diamond)
```

```{r}
arg_contigs_abf <- arg_contigs %>%
  group_by(sample_id, Antibiotic_Family, Surface) %>%
  summarise(abun = sum(abun), .groups = "drop") %>%
  mutate(rela = abun / sum(abun), .by = "sample_id") %>%
  mutate(highlight = any(rela >= .05), .by = Antibiotic_Family)

arg_reads_abf <- arg_reads %>%
  group_by(sample_id, Antibiotic_Family, Surface) %>%
  summarise(abun = sum(abun), .groups = "drop") %>%
  mutate(rela = abun / sum(abun), .by = "sample_id") %>%
  mutate(highlight = any(rela >= .05), .by = Antibiotic_Family)
```

```{r}
shared_species <- union(
  filter(arg_contigs_sp, highlight) %>% pull(species_diamond) %>% unique,
  filter(bac_reads_sp, highlight) %>% pull(species_taxizedb) %>% unique
)
shared_species <- shared_species[c(setdiff(1:length(shared_species), 
                                         which(shared_species == "Unknown")), 
                                 which(shared_species == "Unknown"))]
shared_species <- c(shared_species, "Others")


shared_genus <- union(
  filter(arg_contigs_gen, highlight) %>% pull(genus_diamond) %>% unique,
  filter(bac_reads_gen, highlight) %>% pull(genus) %>% unique
)
shared_genus <- shared_genus[c(setdiff(1:length(shared_genus), 
                                         which(shared_genus == "Unknown")), 
                                 which(shared_genus == "Unknown"))]
shared_genus <- c(shared_genus, "Others")


shared_family <- union(
  filter(arg_contigs_fam, highlight) %>% pull(family_diamond) %>% unique,
  filter(bac_reads_fam, highlight) %>% pull(family) %>% unique
)
shared_family <- shared_family[c(setdiff(1:length(shared_family), 
                                         which(shared_family == "Unknown")), 
                                 which(shared_family == "Unknown"))]
shared_family <- c(shared_family, "Others")

shared_phylum <- union(
  filter(arg_contigs_phy, highlight) %>% pull(phylum_diamond) %>% unique,
  filter(bac_reads_phy, highlight) %>% pull(phylum) %>% unique
)
shared_phylum <- shared_phylum[c(setdiff(1:length(shared_phylum), 
                                         which(shared_phylum == "Unknown")), 
                                 which(shared_phylum == "Unknown"))]
shared_phylum <- c(shared_phylum, "Others")
```

```{r}
col_Unknown <- "#F0F0F0"
col_Other <- "#F5F5DC"
```


```{r}
color_species <- rownames(qualpalr::qualpal(
  n = length(shared_species) - 2,
  colorspace = list(h = c(0, 360), 
                    s = c(.1, .6), 
                    l = c(.5,0.8)))$RGB)
color_species <- c(color_species, col_Unknown, col_Other)
names(color_species) <- shared_species

color_genus <- rownames(qualpalr::qualpal(
  n = length(shared_genus) - 2,
  colorspace = list(h = c(0, 360), 
                    s = c(.1, .6), 
                    l = c(.5,0.8)))$RGB)
color_genus <- c(color_genus, col_Unknown, col_Other)
names(color_genus) <- shared_genus

color_family <- rownames(qualpalr::qualpal(
  n = length(shared_family) - 2,
  colorspace = list(h = c(0, 360), 
                    s = c(.1, .6), 
                    l = c(.55,0.8)))$RGB)
color_family <- c(color_family, col_Unknown, col_Other)
names(color_family) <- shared_family

color_phylum <- rownames(qualpalr::qualpal(
  n = length(shared_phylum) - 2,
  colorspace = list(h = c(0, 360), 
                    s = c(.1, .5), 
                    l = c(.55,0.8)))$RGB)
color_phylum <- c(color_phylum, col_Unknown, col_Other)
names(color_phylum) <- shared_phylum
```

```{r}
shared_abf <- union(
  filter(arg_contigs_abf, highlight) %>% pull(Antibiotic_Family) %>% unique,
  filter(arg_reads_abf, highlight) %>% pull(Antibiotic_Family) %>% unique
)
shared_abf <- shared_abf[c(setdiff(1:length(shared_abf), 
                                         which(shared_abf == "Unknown")), 
                                 which(shared_abf == "Unknown"))]
shared_abf <- c(shared_abf, "Others")

color_abf <- rownames(qualpalr::qualpal(
  n = length(shared_abf) - 2,
  colorspace = list(h = c(0, 360), 
                    s = c(.1, .5), 
                    l = c(.55,0.8)))$RGB)
color_abf <- c(color_abf, col_Unknown, col_Other)
names(color_abf) <- shared_abf
```



```{r}
saveRDS(color_phylum, "cache/color_shared_phylum.rds")
saveRDS(color_family, "cache/color_shared_family.rds")
saveRDS(color_genus, "cache/color_shared_genus.rds")
saveRDS(color_species, "cache/color_shared_species.rds")
```

