---
title: "R Notebook"
---

## MOBILE

```{r, message=FALSE}
library(tidyverse)
library(ComplexHeatmap)
```

## READ DATA

```{r}
meta_sample <- readRDS("../data/R/meta_sample.rds")
arg_contigs <- readRDS("../data/R/arg_contigs.rds")
arg_contigs_mobileOG <- readRDS("../data/R/arg_contigs_mobileOG.rds")
```

```{r}
arg_contigs_mobileOG <- arg_contigs_mobileOG %>%
  mutate(major_mge_short = case_when(
    major_mge == "integration/excision" ~ "I∙E",
    major_mge == "transfer" ~ "T",
    major_mge == "replication/recombination/repair" ~ "R∙R∙R",
    major_mge == "stability/transfer/defense" ~ "S∙T∙D",
    TRUE ~ "ERROR"
  )) %>%
  mutate(minor_mge_short = case_when(
    is.na(minor_mge) ~ "NA",
    minor_mge == "conjugation,relaxosome" ~ "c∙r",
    minor_mge == "replication/recombination/repair" ~ "r∙r∙r",
    minor_mge == "conjugation" ~ "c",
    minor_mge == "initiation,copy number control,plasmid" ~ "i∙cnc∙p",
    TRUE ~ "ERROR"
  )) %>%
  unite(mge_category_short, major_mge_short, minor_mge_short, sep =" | ", remove = F)
```


## MGE

```{r}
mat_MGE <-  arg_contigs %>%
  filter(Antibiotic_Family != "Folate pathway antagonist") %>%
  group_by(sample_id, Gene) %>%
  mutate(is_mobile = if_else(integron_platon == "MGE", TRUE, FALSE)) %>%
  ungroup() %>%
  dplyr::select(sample_id, Gene, is_mobile) %>%
  pivot_wider(names_from = "Gene", values_from = "is_mobile", 
              values_fill = FALSE, values_fn = any) %>%
  ungroup() %>%
  column_to_rownames("sample_id") %>% as.matrix()
mat_MGE <- mat_MGE[meta_sample$sample_id, colSums(mat_MGE) > 0]

taxa_MGE <- arg_contigs %>%
  filter(Antibiotic_Family != "Folate pathway antagonist") %>%
  filter(Gene %in% colnames(mat_MGE)) %>%
  dplyr::select(Gene, Antibiotic_Family) %>%
  distinct() %>%
  mutate(Antibiotic_Family = fct_infreq(Antibiotic_Family)) %>%
  arrange(Antibiotic_Family) %>%  
  mutate(Gene = factor(Gene, levels = unique(Gene)))

mat_MGE <- mat_MGE[, taxa_MGE$Gene]
```


```{r}
# Colori automatici ggplot-like per 5 fattori
surface_levels <- c("dirty drain", "clean drain", "dirty surface", "clean surface", "carcass")
surface_colors <- scales::hue_pal()(length(surface_levels))
names(surface_colors) <- surface_levels

# Colori automatici ggplot-like per 3 fattori
surface_type_levels <- c("dirty", "clean", "carcass")
surface_type_colors <- scales::viridis_pal()(length(surface_type_levels))
names(surface_type_colors) <- surface_type_levels

# Colori automatici ggplot-like per 2 fattori
presence_levels <- c("0", "1")
presence_colors <- scales::viridis_pal(option = "E")(length(presence_levels))
names(presence_colors) <- presence_levels

library(RColorBrewer)
antibiotic_families <- unique(taxa_MGE$Antibiotic_Family)
antibiotic_family_colors <- setNames(brewer.pal(n = length(antibiotic_families), 
                                                name = "Paired"), antibiotic_families)

# Colore per TRUE/FALSE
#heat_colors <- c("0" = "navy", "1" = "yellow")
```


```{r}
row_annot_MGE <- rowAnnotation(
  Surface = meta_sample$Surface,
  Surface_Type = meta_sample$Surface_Type,
  col = list(Surface = surface_colors,
             Surface_Type = surface_type_colors),
  annotation_width = unit(0.4, "cm")
)

col_annot_MGE <- HeatmapAnnotation(
  "Antibiotic Family" = taxa_MGE$Antibiotic_Family,
  col = list("Antibiotic Family" = antibiotic_family_colors),
  show_annotation_name = FALSE
)
```

```{r, fig.width=8, fig.height=6}
# Prima heatmap
ht_MGE <- Heatmap(mat_MGE * 1, # converte TRUE/FALSE in numerico
               name = "Presence",
               col = presence_colors,
               clustering_distance_rows = "binary",
               clustering_method_rows = "complete",
               cluster_columns = FALSE,
               show_row_names = TRUE,
               show_column_names = TRUE,
               row_names_side = "left",
               left_annotation = row_annot_MGE,
               top_annotation = col_annot_MGE,
               show_heatmap_legend = FALSE,
               rect_gp = gpar(col = "grey", lwd = 1))
ht_MGE
```

## LGT

```{r}
mat_LGT <-  arg_contigs %>%
  filter(Antibiotic_Family != "Folate pathway antagonist") %>%
  group_by(sample_id, Gene) %>%
  mutate(is_mobile = if_else(plasmid_waafle == "LGT", TRUE, FALSE)) %>%
  ungroup() %>%
  dplyr::select(sample_id, Gene, is_mobile) %>%
  pivot_wider(names_from = "Gene", values_from = "is_mobile", 
              values_fill = FALSE, values_fn = any) %>%
  ungroup() %>%
  column_to_rownames("sample_id") %>% as.matrix()
mat_LGT <- mat_LGT[meta_sample$sample_id, colSums(mat_LGT) > 0]

taxa_LGT <- arg_contigs %>%
  filter(Antibiotic_Family != "Folate pathway antagonist") %>%
  filter(Gene %in% colnames(mat_LGT)) %>%
  dplyr::select(Gene, Antibiotic_Family) %>%
  distinct() %>%
  mutate(Antibiotic_Family = factor(Antibiotic_Family, levels = levels(taxa_MGE$Antibiotic_Family))) %>%
  arrange(Antibiotic_Family) 

mat_LGT <- mat_LGT[, taxa_LGT$Gene]
```

```{r}
row_annot_LGT <- rowAnnotation(
  Surface = meta_sample$Surface,
  Surface_Type = meta_sample$Surface_Type,
  col = list(Surface = surface_colors,
             Surface_Type = surface_type_colors),
  annotation_width = unit(0.4, "cm")
)

col_annot_LGT <- HeatmapAnnotation(
  "Antibiotic Family" = taxa_LGT$Antibiotic_Family,
  col = list("Antibiotic Family" = antibiotic_family_colors),
  show_annotation_name = FALSE
)
```

```{r, fig.width=8, fig.height=6}
# Seconda heatmap
ht_LGT <- Heatmap(mat_LGT * 1, # converte TRUE/FALSE in numerico
               name = "Presence",
               col = presence_colors,
               clustering_distance_rows = "binary",
               clustering_method_rows = "complete",
               cluster_columns = FALSE,
               show_row_names = TRUE,
               show_column_names = TRUE,
               row_names_side = "left",
               left_annotation = row_annot_LGT,
               top_annotation = col_annot_LGT,
               show_heatmap_legend = FALSE,
               rect_gp = gpar(col = "grey", lwd = 1)) 
ht_LGT
```




```{r}
legend_presence <- Legend(
  title = "Presence",
  at = c("0", "1"),
  labels = c("TRUE", "FALSE"),
  direction = "horizontal", 
  legend_gp = gpar(fill = presence_colors)
)
```


```{r,fig.width=15, fig.height=6, warning=FALSE}
library(grid)

# Combina le due heatmap
ht_combined <- ht_MGE + ht_LGT

png(filename = "../plots/figure6.png", width = 2*4500, height = 2*1800, res = 2*300)
# Disegna la heatmap
p_combined <- draw(ht_combined,
                   heatmap_legend_side = "bottom",
                   heatmap_legend_list = list(legend_presence),
                   #annotation_legend_side = "bottom",
                   merge_legends = FALSE)

# Aggiungi etichette con grid
grid.text("a", x = unit(0.095, "npc"), y = unit(0.98, "npc"), 
          gp = gpar(fontsize = 16, fontface = "bold"), just = "left")

grid.text("b", x = unit(0.68, "npc"), y = unit(0.98, "npc"), 
          gp = gpar(fontsize = 16, fontface = "bold"), just = "left")

dev.off()
```

# MobileOG

```{r}
df <- arg_contigs_mobileOG %>%
  distinct(sample_id, antibiotic_amr, mge_category_short) %>%
  mutate(sample_id = factor(sample_id,
                            levels = c("DD1_ita_i", "DD2_ita_i", "DD3_ita_i", "DD4_ita_i",
                                       "DS1_ita_i", "DS2_ita_i", "DS3_ita_i", "DS4_ita_i",
                                       "CD1_ita_i", "CD2_ita_i", "CD3_ita_i", "CD4_ita_i",
                                       "CS1_ita_i", "CS2_ita_i", "CS3_ita_i", "CS4_ita_i",
                                       "CAR1_ita_i", "CAR2_ita_i", "CAR3_ita_i", "CAR4_ita_i")),
         antibiotic_amr = fct_infreq(antibiotic_amr),
         mge_category_short = fct_infreq(mge_category_short)
         )
```

```{r}
cell_w <- 0.9; cell_h <- 0.9
grid_w <- cell_w/3   # "sub_w"
grid_h <- cell_h/3
dot_w <- cell_w * 0.26
dot_h <- cell_h * 0.26

layout_232 <- tribble(
  ~idx, ~col, ~row,
  1,     1.5,  1,
  2,     2.5,  1,
  3,     1,    2,
  4,     2,    2,
  5,     3,    2,
  6,     1.5,  3,
  7,     2.5,  3
) %>%
  mutate(
    dx = (col - 2) * grid_w,
    dy = (2 - row) * grid_h
  )
```

```{r}
plot_df <- df %>%
    mutate(
    xf  = as.integer(sample_id),
    yf  = as.integer(antibiotic_amr),
    idx = as.integer(mge_category_short) 
  ) %>%
  left_join(layout_232, by = join_by(idx)) %>%
  mutate(
    x_pos = xf + dx,
    y_pos = yf + dy
  )
```


```{r, fig.width=12, fig.height=6}
p_mobileOG <- meta_sample %>%
  select(sample_id, Surface, Surface_Type) %>%
  right_join(plot_df, by = "sample_id") %>%
  ggplot() +
  geom_tile(
    aes(x = xf, y = yf, color = Surface),
    width = cell_w, height = cell_h, fill = NA, linewidth = 0.5
  ) +
  geom_tile(
    aes(x = x_pos, y = y_pos, fill = mge_category_short),
    width = dot_w, height = dot_h, color = NA
  ) +
  scale_x_continuous(
    breaks = seq_along(levels(df$sample_id)),
    labels = levels(df$sample_id),
    expand = expansion(mult = 0.02)
  ) +
  scale_y_continuous(
    breaks = seq_along(levels(df$antibiotic_amr)),
    labels = levels(df$antibiotic_amr),
    expand = expansion(mult = 0.02)
  ) +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1),
        axis.title = element_blank()) +
  labs(fill = "MGE Category")
p_mobileOG
```

```{r}
png(filename = "../plots/mobileOG_amr.png", width = 12*300, height = 6*300, res = 300)
p_mobileOG
dev.off()
```

