---
title: "R Notebook"
output: html_notebook
---

```{r, warning=FALSE}
library(tidyverse)
library(Rtsne)
```

```{r}
meta_sample <- readRDS("../data/R/meta_sample.rds")
bac_reads <- readRDS("../data/R/bac_reads.rds") 
arg_reads <- readRDS("../data/R/arg_reads.rds")
arg_contigs <- readRDS("../data/R/arg_contigs.rds")
```

```{r}
abun_bac_sp_reads <- bac_reads %>%
  select(sample_id, species, abun) %>%
  pivot_wider(names_from = "species", values_from = "abun",values_fill = 0) %>%
  column_to_rownames("sample_id")

abun_arg_reads_gene <- arg_reads %>%
  select(sample_id, Gene, abun) %>%
  pivot_wider(names_from = "Gene", values_from = "abun",values_fill = 0) %>%
  column_to_rownames("sample_id")

abun_arg_contigs_gene <- arg_contigs %>%
  select(sample_id, Gene, abun) %>%
  group_by(sample_id, Gene) %>%
  summarise(abun = sum(abun), .groups = "drop") %>%
  pivot_wider(names_from = "Gene", values_from = "abun", values_fill = 0) %>%
  column_to_rownames("sample_id")
```

```{r}
make_tsne <- function(abun, meta, seed = 42){
  
  set.seed(seed)
  
  p <- abun %>%
    zCompositions::cmultRepl(method = "CZM", z.delete = FALSE) %>%
    vegan::decostand("clr") %>%
    dist %>%
    Rtsne::Rtsne(is_distance=TRUE,
                 perplexity = 4, theta = .5, 
                 pca = TRUE, max_iter = 10000) %>%
    .$Y %>% as_tibble() %>%
    cbind(tibble(sample_id = rownames(abun))) %>%
    relocate(sample_id) %>%
  left_join(meta, by = "sample_id") %>%
  ggplot(aes(x = V1, y = V2, fill = Surface)) +
  geom_point(size = 3, shape = 21) +
  stat_ellipse(aes(group = Surface_Type, color = Surface_Type)) +
  scale_color_viridis_d() +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank())) 
  
  return(p)
}
```


```{r, warning=FALSE, warning=FALSE}
p_beta_tsne_bac_sp_reads <- make_tsne(abun_bac_sp_reads, meta_sample)
p_beta_tsne_arg_reads_gene <- make_tsne(abun_arg_reads_gene, meta_sample)
p_beta_tsne_arg_contigs_gene <- make_tsne(abun_arg_contigs_gene, meta_sample)
```

```{r, fig.width=12, fig.height=5, message=FALSE, warning=FALSE}
p <- ggpubr::ggarrange(
  
  p_beta_tsne_bac_sp_reads, p_beta_tsne_arg_reads_gene, p_beta_tsne_arg_contigs_gene,
  labels = c("a", "b", "c"),
  common.legend = TRUE, ncol = 3, legend = "top", label.x = .025
  
)
p
```


```{r}
png("../plots/plot_beta.png", width = 3600, height = 1500, res = 300)
p
dev.off()
```

```{r}
pdf("../plots/plot_beta.pdf", width = 12, height = 5)
p
dev.off()
```

# Adonis

```{r, message=FALSE, warning=FALSE}
aitch_bac_read_sp <- abun_bac_sp_reads %>%
  zCompositions::cmultRepl(method = "CZM", z.delete = FALSE) %>%
  vegan::decostand("clr") %>%
  dist()

aitch_arg_read_gene <- abun_arg_reads_gene %>%
  zCompositions::cmultRepl(method = "CZM", z.delete = FALSE) %>%
  vegan::decostand("clr") %>%
  dist()

aitch_arg_contig_gene <- abun_arg_contigs_gene %>%
  zCompositions::cmultRepl(method = "CZM", z.delete = FALSE) %>%
  vegan::decostand("clr") %>%
  dist()
```

```{r}
adonis_bac_read_sp_surface <- vegan::adonis2(aitch_bac_read_sp ~ Surface, data = meta_sample)
adonis_arg_read_gene_surface <- vegan::adonis2(aitch_arg_read_gene ~ Surface, data = meta_sample)
adonis_arg_contig_gene_surface <- vegan::adonis2(aitch_arg_contig_gene ~ Surface, data = meta_sample)

adonis_bac_read_sp_surfacetype <- vegan::adonis2(aitch_bac_read_sp ~ Surface_Type, data = meta_sample)
adonis_arg_read_gene_surfacetype <- vegan::adonis2(aitch_arg_read_gene ~ Surface_Type, data = meta_sample)
adonis_arg_contig_gene_surfacetype <- vegan::adonis2(aitch_arg_contig_gene ~ Surface_Type, data = meta_sample)

```

