---
title: "R Notebook"
output: html_notebook
---

## MOBILE

```{r, message=FALSE}
library(tidyverse)
library(ComplexHeatmap)
```

## READ DATA

```{r}
meta_sample <- readRDS("../data/R/meta_sample.rds")
arg_contigs <- readRDS("../data/R/arg_contigs.rds")
```

## MGE

```{r}
mat_MGE <-  arg_contigs %>%
  group_by(sample_id, Gene) %>%
  mutate(is_mobile = if_else(integron_platon == "MGE", TRUE, FALSE)) %>%
  ungroup() %>%
  dplyr::select(sample_id, Gene, is_mobile) %>%
  pivot_wider(names_from = "Gene", values_from = "is_mobile", 
              values_fill = FALSE, values_fn = any) %>%
  ungroup() %>%
  column_to_rownames("sample_id") %>% as.matrix()
mat_MGE <- mat_MGE[meta_sample$sample_id, colSums(mat_MGE) > 0]

taxa_MGE <- arg_contigs %>%
  filter(Gene %in% colnames(mat_MGE)) %>%
  select(Gene, Antibiotic_Family) %>%
  distinct() %>%
  mutate(Antibiotic_Family = fct_infreq(Antibiotic_Family)) %>%
  arrange(Antibiotic_Family) %>%  
  mutate(Gene = factor(Gene, levels = unique(Gene)))

mat_MGE <- mat_MGE[, taxa_MGE$Gene]
```


```{r}
# Colori automatici ggplot-like per 5 fattori
surface_levels <- c("dirty drain", "clean drain", "dirty surface", "clean surface", "carcass")
surface_colors <- scales::hue_pal()(length(surface_levels))
names(surface_colors) <- surface_levels

# Colori automatici ggplot-like per 3 fattori
surface_type_levels <- c("dirty", "clean", "carcass")
surface_type_colors <- scales::viridis_pal()(length(surface_type_levels))
names(surface_type_colors) <- surface_type_levels

# Colori automatici ggplot-like per 2 fattori
presence_levels <- c("0", "1")
presence_colors <- scales::viridis_pal(option = "E")(length(presence_levels))
names(presence_colors) <- presence_levels

library(RColorBrewer)
antibiotic_families <- unique(taxa_MGE$Antibiotic_Family)
antibiotic_family_colors <- setNames(brewer.pal(n = length(antibiotic_families), 
                                                name = "Paired"), antibiotic_families)

# Colore per TRUE/FALSE
#heat_colors <- c("0" = "navy", "1" = "yellow")
```


```{r}
row_annot_MGE <- rowAnnotation(
  Surface = meta_sample$Surface,
  Surface_Type = meta_sample$Surface_Type,
  col = list(Surface = surface_colors,
             Surface_Type = surface_type_colors),
  annotation_width = unit(0.4, "cm")
)

col_annot_MGE <- HeatmapAnnotation(
  "Antibiotic Family" = taxa_MGE$Antibiotic_Family,
  col = list("Antibiotic Family" = antibiotic_family_colors),
  show_annotation_name = FALSE
)
```

```{r, fig.width=8, fig.height=6}
# Prima heatmap
ht_MGE <- Heatmap(mat_MGE * 1, # converte TRUE/FALSE in numerico
               name = "Presence",
               col = presence_colors,
               clustering_distance_rows = "binary",
               clustering_method_rows = "complete",
               cluster_columns = FALSE,
               show_row_names = TRUE,
               show_column_names = TRUE,
               row_names_side = "left",
               left_annotation = row_annot_MGE,
               top_annotation = col_annot_MGE,
               show_heatmap_legend = FALSE,
               rect_gp = gpar(col = "grey", lwd = 1))
ht_MGE
```

## LGT

```{r}
mat_LGT <-  arg_contigs %>%
  group_by(sample_id, Gene) %>%
  mutate(is_mobile = if_else(plasmid_waafle == "LGT", TRUE, FALSE)) %>%
  ungroup() %>%
  dplyr::select(sample_id, Gene, is_mobile) %>%
  pivot_wider(names_from = "Gene", values_from = "is_mobile", 
              values_fill = FALSE, values_fn = any) %>%
  ungroup() %>%
  column_to_rownames("sample_id") %>% as.matrix()
mat_LGT <- mat_LGT[meta_sample$sample_id, colSums(mat_LGT) > 0]

taxa_LGT <- arg_contigs %>%
  filter(Gene %in% colnames(mat_LGT)) %>%
  select(Gene, Antibiotic_Family) %>%
  distinct() %>%
  mutate(Antibiotic_Family = factor(Antibiotic_Family, levels = levels(taxa_MGE$Antibiotic_Family))) %>%
  arrange(Antibiotic_Family) 

mat_LGT <- mat_LGT[, taxa_LGT$Gene]
```

```{r}
row_annot_LGT <- rowAnnotation(
  Surface = meta_sample$Surface,
  Surface_Type = meta_sample$Surface_Type,
  col = list(Surface = surface_colors,
             Surface_Type = surface_type_colors),
  annotation_width = unit(0.4, "cm")
)

col_annot_LGT <- HeatmapAnnotation(
  "Antibiotic Family" = taxa_LGT$Antibiotic_Family,
  col = list("Antibiotic Family" = antibiotic_family_colors),
  show_annotation_name = FALSE
)
```

```{r, fig.width=8, fig.height=6}
# Seconda heatmap
ht_LGT <- Heatmap(mat_LGT * 1, # converte TRUE/FALSE in numerico
               name = "Presence",
               col = presence_colors,
               clustering_distance_rows = "binary",
               clustering_method_rows = "complete",
               cluster_columns = FALSE,
               show_row_names = TRUE,
               show_column_names = TRUE,
               row_names_side = "left",
               left_annotation = row_annot_LGT,
               top_annotation = col_annot_LGT,
               show_heatmap_legend = FALSE,
               rect_gp = gpar(col = "grey", lwd = 1)) 
ht_LGT
```




```{r}
legend_presence <- Legend(
  title = "Presence",
  at = c("0", "1"),
  labels = c("TRUE", "FALSE"),
  direction = "horizontal", 
  legend_gp = gpar(fill = presence_colors)
)
```


```{r,fig.width=15, fig.height=6, warning=FALSE}
library(grid)

# Combina le due heatmap
ht_combined <- ht_MGE + ht_LGT

png(filename = "../plots/mobiles.png", width = 4500, height = 1800, res = 300)
# Disegna la heatmap
p_combined <- draw(ht_combined,
                   heatmap_legend_side = "bottom",
                   heatmap_legend_list = list(legend_presence),
                   #annotation_legend_side = "bottom",
                   merge_legends = FALSE)

# Aggiungi etichette con grid
grid.text("a", x = unit(0.095, "npc"), y = unit(0.98, "npc"), 
          gp = gpar(fontsize = 16, fontface = "bold"), just = "left")

grid.text("b", x = unit(0.68, "npc"), y = unit(0.98, "npc"), 
          gp = gpar(fontsize = 16, fontface = "bold"), just = "left")

dev.off()
```




