---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(mgnet)
```

```{r}
arg <- readRDS("../data/R/arg.rds") %>%
  filter_meta(Country == "Italy", Tecnology == "Illumina") 
arg
```

```{r}
arg %>%
  split_sample(Level) %>%
  filter_taxa(sum(abun) > 0) %>%
  mutate_taxa(prevalence = sum(abun>0) / length(abun),
              sum_taxa = sum(abun)) %>%
  gather_taxa() %>%
  select(-Antibiotic_Family) %>%
  pivot_longer(-c(mgnet, taxa_id), names_to = "measurments", values_to = "values") %>%
  ggplot(aes(x = values, fill = measurments)) +
  geom_histogram(bins = 20, color = "lightgray") +
  facet_wrap(~mgnet+measurments, scales = "free") +
  theme_bw() +
  scale_x_log10() +
  theme(legend.position = "top")
```

```{r}
arg %>%
  split_sample(Level) %>%
  filter_taxa(sum(abun) > 0) %>%
  mutate_meta(
    richness = sum(abun>0),
    pielou = vegan::diversity(abun) / log(length(abun>0))
  ) %>%
  gather_meta() %>%
  select(Level, sample_id, Surface, richness, pielou) %>%
  pivot_longer(-c(Level, sample_id, Surface), names_to = "measurments", values_to = "values") %>%
  ggplot(aes(x = Level, y = values, group = Level)) +
  geom_boxplot(alpha = .4, outlier.shape = NA) +
  geom_jitter(aes(fill = Surface), width = .25, size = 2.5, pch = 21) + 
  facet_wrap(~measurments, scales = "free") +
  theme_bw() +
  theme(legend.position = "top")
```

```{r}
p_shannon <- arg %>%
  split_sample(Level) %>%
  filter_taxa(sum(abun) > 0) %>%
  mutate_meta(
    pielou = vegan::diversity(abun[abun>0]) / log(length(abun[abun>0]))) %>%
  gather_meta() %>%
  select(Level, sample_id, Surface, pielou) %>%
  ggplot(aes(x = Surface, y = pielou, fill = Level)) +
  geom_boxplot() +
  facet_wrap(~Surface, scales = "free_x", ncol = 5) +
  theme_bw() +
  theme(legend.position = "top")
p_shannon
```

## Filtering

```{r, fig.width=10, fig.height=5}
processed_data  <- arg %>%
  filter_meta(!(Level == "contigs" & Surface == "carcass")) %>%
  split_sample(Level, Surface) %>%
  filter_taxa(sum(abun) > 0) %>%
  mutate_taxa(prevalence = sum(abun>0) / length(abun),
              sum_taxa = sum(abun)) %>%
  gather_mgnet() %>%
  select(Level, Surface, sample_id, prevalence, sum_taxa) %>%
  pivot_longer(-c(Level, Surface, sample_id), names_to = "measurments", values_to = "values") %>%
  mutate(draw_line_sum = measurments == "sum_taxa")

processed_data %>%
  ggplot(aes(x = values, fill = Level)) +
  geom_histogram(aes(y = after_stat(density)),
    bins = 10, color = "lightgray", position = "dodge") +
  facet_wrap(~measurments + Surface, scales = "free", ncol = 5) +
  theme_bw() +
  scale_x_log10() +
  theme(legend.position = "top", axis.text.y = element_blank()) +
  geom_vline(data = filter(processed_data, draw_line_sum), 
             aes(xintercept = 5), linetype = "dashed", color = "black") 

rm(processed_data)
```

```{r}
arg_split_filt <- arg %>%
  mutate_meta(sum_orig = sum(abun)) %>%
  split_sample(Level, Surface) %>%
  mutate_taxa(
    prev = sum(abun>0) / length(abun),
    sum_taxa = sum(abun)
  ) 

for(name in names(arg_split_filt)){
  
  if(str_detect(name, "read")){
    arg_split_filt[[name]] <- arg_split_filt[[name]] %>%
      filter_taxa(prev >= .5 & sum_taxa >= 10)
  } else {
    arg_split_filt[[name]] <- arg_split_filt[[name]] %>%
      filter_taxa(sum_taxa > 0)
  }
  
} 
rm(name)

arg_split_filt <- arg_split_filt %>%
  mutate_meta(percentage_preserved_counts = sum(abun)/sum_orig)

ntaxa(arg_split_filt)
```

```{r}
gather_meta(arg_split_filt) %>%
  filter(Level == "read") %>%
  ggplot(aes(x = percentage_preserved_counts, fill = Surface)) +
  geom_histogram(bins = 10, position = "stack",color = "black")
```

## Make CLR

```{r}
arg_split_filt <- arg_split_filt %>%
  set_norm_CLR()

union_filt_taxa <- reduce(taxa_id(arg_split_filt), union) %>% unique
inter_filt_taxa <- reduce(taxa_id(arg_split_filt), intersect) %>% unique
```

## Make Tsne

```{r, warning=FALSE}
set.seed(4)
arg[, union_filt_taxa] %>%
  set_norm_CLR() %>%
  norm %>% dist %>%
  Rtsne::Rtsne(is_distance=TRUE,
               perplexity = 4, theta = .25, 
               pca = TRUE, max_iter = 1000) %>%
  .$Y %>% as_tibble() %>%
  cbind(tibble(sample_id = sample_id(arg))) %>%
  relocate(sample_id) %>%
  left_join(meta(arg,"tbl"), by = "sample_id") %>%
  ggplot(aes(x = V1, y = V2, fill = Surface, shape = Level)) +
  geom_point(size = 3) +
  stat_ellipse(aes(group = Level, color = Level)) +
  scale_shape_manual(values = c("read" = 21,"contigs" = 23)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank()) +
  scale_fill_brewer(palette = "Set2")
  
# arg[, union_filt_taxa] %>%
#   set_norm_CLR() %>%
#   norm %>% dist %>%
#   cmdscale() %>%
#   as_tibble(rownames = "sample_id") %>%
#   left_join(meta(arg,"tbl"), by = "sample_id") %>%
#   ggplot(aes(x = V1, y = V2, fill = Surface)) +
#   geom_point(shape = 21) +
#   stat_ellipse(aes(group = Level, color = Level))
```

## UMAP

```{r}
library(umap)

custom.config <- umap.defaults
custom.config$random_state <- 42
custom.config$n_neighbors <- 4
custom.config$n_epochs <- 500
custom.config$spread: .5
custom.config$min_dist <- .5


umap_arg <- arg[, union_filt_taxa] %>%
  set_norm_CLR() %>%
  norm %>%
  umap(config=custom.config)
```

```{r, warning=FALSE}
umap_arg$layout %>%
  as_tibble(rownames = "sample_id") %>%
  left_join(meta(arg,"tbl"), by = "sample_id") %>%
  ggplot(aes(x = V1, y = V2, fill = Surface, shape = Level)) +
  geom_point(size = 3) +
  stat_ellipse(aes(group = Level, color = Level)) +
  scale_shape_manual(values = c("read" = 21,"contigs" = 23)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank())
```


## Bacteria

```{r}
bac <- readRDS("../data/R/bac.rds")
gen <- readRDS("../data/R/gen.rds")
```

```{r}
fam <- bac %>%
  filter_meta(Country == "Italy", Tecnology == "Illumina") %>%
  gather_mgnet() %>%
  select(sample_id,experiment_id, rela, Surface, family) %>%
  group_by(experiment_id, sample_id, family, Surface) %>%
  summarize(rela = sum(rela), .groups = "drop") 

top_families <- fam %>%
  group_by(family) %>%
  summarize(max_rela = max(rela), .groups = "drop") %>%
  filter(max_rela > .075) %>%
  pull(family)

fam <- fam %>%
  mutate(family = ifelse(!family %in% top_families, "Other", family)) %>%
  group_by(experiment_id, sample_id, family, Surface) %>%
  summarize(rela = sum(rela), .groups = "drop") 

palette_fam <- colormap_categories(c(top_families, "Other"), colorspace = "pretty")

fam %>%
  mutate(family = ifelse(!family %in% top_families, "Other", family)) %>%
  ggplot(aes(x = experiment_id, y = rela, fill = family)) +
  geom_bar(stat = "identity") +
  #theme(legend.position = "none") +
  facet_wrap(~ Surface, scales = "free_x", ncol = 5) +
  scale_fill_manual(values = palette_fam, breaks = names(palette_fam)) +
  theme_bw() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_blank(),
        axis.title.x = element_blank())
```

```{r}
bac %>%
  filter_taxa(sum(abun) > 0) %>%
  mutate_taxa(prevalence = sum(abun>0) / length(abun),
              log10_sum_taxa = log10(sum(abun))) %>%
  taxa(.fmt = "tbl") %>%
  select(taxa_id, prevalence, log10_sum_taxa) %>%
  pivot_longer(-taxa_id, names_to = "measurments", values_to = "values") %>%
  ggplot(aes(x = values, fill = measurments)) +
  geom_histogram(bins = 20, color = "lightgray") +
  facet_wrap(~measurments, scales = "free") +
  theme_bw() +
  theme(legend.position = "top")
```

```{r, warning=FALSE}
set.seed(4)
bac %>%
  filter_taxa(sum(abun) >= 50) %>%
  set_norm_CLR() %>%
  norm %>% dist %>%
  Rtsne::Rtsne(is_distance=TRUE,
               perplexity = 4, theta = .25, 
               pca = TRUE, max_iter = 10000) %>%
  .$Y %>% as_tibble() %>%
  cbind(tibble(sample_id = sample_id(bac))) %>%
  relocate(sample_id) %>%
  left_join(meta(bac,"tbl"), by = "sample_id") %>%
  unite("Tecnology_Country", c(Tecnology, Country)) %>%
  ggplot(aes(x = V1, y = V2, fill = Surface)) +
  geom_point(size = 3, shape = 21) +
  stat_ellipse(aes(group = Tecnology_Country, color = Tecnology_Country)) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank())
```

```{r, warning=FALSE}
custom.config <- umap.defaults
custom.config$random_state <- 42
custom.config$n_neighbors <- 4
custom.config$n_epochs <- 500
custom.config$spread: 1
custom.config$min_dist <- .5


umap_arg <- bac %>%
  filter_taxa(sum(abun) >= 50) %>%
  set_norm_CLR() %>%
  norm %>%
  umap(config=custom.config)

umap_arg$layout %>%
  as_tibble(rownames = "sample_id") %>%
  left_join(meta(bac,"tbl"), by = "sample_id") %>%
  unite("Tecnology_Country", c(Tecnology, Country)) %>%
  ggplot(aes(x = V1, y = V2, fill = Surface)) +
  geom_point(size = 3, shape = 21) +
  stat_ellipse(aes(group = Tecnology_Country, color = Tecnology_Country)) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank())
```

```{r, warning=FALSE}
set.seed(3)
sub_bac <- bac %>%
  filter_meta(Tecnology == "Illumina" & Country == "Italy")

tsne_bac <- sub_bac %>%
  filter_taxa(sum(abun) >= 50) %>%
  set_norm_CLR() %>%
  norm %>% dist %>%
  Rtsne::Rtsne(is_distance=TRUE,
               perplexity = 4, theta = .25, 
               pca = TRUE, max_iter = 10000) %>%
  .$Y %>% as_tibble() %>%
  cbind(tibble(sample_id = sample_id(sub_bac))) %>%
  relocate(sample_id) %>%
  left_join(meta(sub_bac,"tbl"), by = "sample_id") %>%
  mutate(Surface_Type = case_when(
    str_detect(Surface, "clean") ~ "clean",
    str_detect(Surface, "dirty") ~ "dirty", 
    str_detect(Surface, "carcass") ~ "carcass"
  )) %>%
  ggplot(aes(x = V1, y = V2, fill = Surface)) +
  geom_point(size = 3, shape = 21) +
  stat_ellipse(aes(group = Surface_Type, color = Surface_Type)) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank())
tsne_bac
```



```{r, warning=FALSE}
set.seed(42)

sub_arg <- arg[, union_filt_taxa] %>%
  filter_meta(Level == "contigs", Tecnology == "Illumina", Country == "Italy")

tsne_contigs <- sub_arg %>%
  set_norm_CLR() %>%
  norm %>% dist %>%
  Rtsne::Rtsne(is_distance=TRUE,
               perplexity = 4, theta = .25, 
               pca = TRUE, max_iter = 10000) %>%
  .$Y %>% as_tibble() %>%
  cbind(tibble(sample_id = sample_id(sub_arg))) %>%
  relocate(sample_id) %>%
  left_join(meta(sub_arg,"tbl"), by = "sample_id") %>%
  mutate(Surface_Type = case_when(
    str_detect(Surface, "clean") ~ "clean",
    str_detect(Surface, "dirty") ~ "dirty", 
    str_detect(Surface, "carcass") ~ "carcass"
  )) %>%
  ggplot(aes(x = V1, y = V2, fill = Surface)) +
  geom_point(size = 3, shape = 21) +
  stat_ellipse(aes(group = Surface_Type, color = Surface_Type)) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank())

tsne_contigs
```

```{r, warning=FALSE}
set.seed(42)

sub_arg <- arg[, union_filt_taxa] %>%
  filter_meta(Level == "read", Tecnology == "Illumina", Country == "Italy")

tsne_read <- sub_arg %>%
  set_norm_CLR() %>%
  norm %>% dist %>%
  Rtsne::Rtsne(is_distance=TRUE,
               perplexity = 4, theta = .25, 
               pca = TRUE, max_iter = 10000) %>%
  .$Y %>% as_tibble() %>%
  cbind(tibble(sample_id = sample_id(sub_arg))) %>%
  relocate(sample_id) %>%
  left_join(meta(sub_arg,"tbl"), by = "sample_id") %>%
  mutate(Surface_Type = case_when(
    str_detect(Surface, "clean") ~ "clean",
    str_detect(Surface, "dirty") ~ "dirty", 
    str_detect(Surface, "carcass") ~ "carcass"
  )) %>%
  ggplot(aes(x = V1, y = V2, fill = Surface)) +
  geom_point(size = 3, shape = 21) +
  stat_ellipse(aes(group = Surface_Type, color = Surface_Type)) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.title = element_blank())

tsne_read
```



```{r}
df_arg_families <- read_tsv("../data/RAW/df_arg_families.tsv")

arg_fam <- df_arg_families %>%
  filter(Country == "Italy") %>%
  group_by(sample_id) %>%
  mutate(rela = Contig_coverage/sum(Contig_coverage)) %>%
  ungroup() %>%
  select(sample_id,experiment_id, rela, Surface, family) %>%
  group_by(experiment_id, sample_id, family, Surface) %>%
  summarize(rela = sum(rela), .groups = "drop") 

top_families <- arg_fam %>%
  group_by(family) %>%
  summarize(max_rela = max(rela), .groups = "drop") %>%
  filter(max_rela > .075) %>%
  pull(family)

arg_fam <- arg_fam %>%
  mutate(family = ifelse(!family %in% top_families, "Other", family)) %>%
  group_by(experiment_id, sample_id, family, Surface) %>%
  summarize(rela = sum(rela), .groups = "drop") 

palette_arg_fam <- colormap_categories(c(top_families, "Other"), colorspace = "rainbow")

arg_fam %>%
  mutate(family = ifelse(!family %in% top_families, "Other", family)) %>%
  ggplot(aes(x = experiment_id, y = rela, fill = family)) +
  geom_bar(stat = "identity") +
  #theme(legend.position = "none") +
  facet_wrap(~ Surface, scales = "free_x", ncol = 5) +
  scale_fill_manual(values = palette_arg_fam, breaks = names(palette_arg_fam)) +
  theme_bw() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_blank(),
        axis.title.x = element_blank())
```





## Save Results


```{r}
p_shannon <- bind_rows(
  gather_mgnet(bac), gather_mgnet(arg)
) %>%
  filter(Country == "Italy" & Tecnology == "Illumina") %>%
  mutate(from = case_when(
    is.na(Antibiotic_Family) ~ "bacteria",
    !is.na(Antibiotic_Family) & Level == "read" ~ "arg read",
    !is.na(Antibiotic_Family) & Level == "contigs" ~ "arg contig"
  )) %>%
  group_by(sample_id) %>%
  mutate(Pielou = vegan::diversity(abun[abun>0]) / log(length(abun[abun>0]))) %>% 
  ungroup() %>%
  select(sample_id, from, Pielou, Surface) %>%
  distinct() %>%
  ggplot(aes(x = from, y = Pielou, fill = from)) +
  geom_boxplot() +
  facet_wrap(~Surface, scales = "free_x", ncol = 5) +
  theme_bw() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r, fig.height=10}
fam <- bac %>%
  filter_meta(Country == "Italy", Tecnology == "Illumina") %>%
  gather_mgnet() %>%
  select(sample_id,experiment_id, rela, Surface, family) %>%
  group_by(experiment_id, sample_id, family, Surface) %>%
  summarize(rela = sum(rela), .groups = "drop") 

df_arg_families <- read_tsv("../data/RAW/df_arg_families.tsv")

arg_fam <- df_arg_families %>%
  filter(Country == "Italy") %>%
  group_by(sample_id) %>%
  mutate(rela = Contig_coverage/sum(Contig_coverage)) %>%
  ungroup() %>%
  select(sample_id,experiment_id, rela, Surface, family) %>%
  group_by(experiment_id, sample_id, family, Surface) %>%
  summarize(rela = sum(rela), .groups = "drop") 

top_families <- bind_rows(cbind(fam, "from" = "bac"),
                          cbind(arg_fam, "from" = "arg")) %>%
  group_by(family, from) %>%
  summarize(max_rela = max(rela), .groups = "drop") %>%
  filter(max_rela > .075) %>%
  pull(family)

palette_arg_fam <- colormap_categories(c(top_families, "Other"), colorspace = "pretty")


p_composition <- bind_rows(cbind(fam, "from" = "bac"),
          cbind(arg_fam, "from" = "arg")) %>%
  mutate(family = ifelse(!family %in% top_families, "Other", family)) %>%
  group_by(experiment_id, sample_id, family, Surface, from) %>%
  summarize(rela = sum(rela), .groups = "drop") %>%
  ggplot(aes(x = experiment_id, y = rela, fill = family)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ from + Surface, scales = "free_x", ncol = 5) +
  scale_fill_manual(values = palette_arg_fam, breaks = names(palette_arg_fam)) +
  theme_bw() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  guides(fill=guide_legend(ncol=8))
```




```{r}
library(ggpubr)
```

```{r, fig.width=16, fig.height=16, warning=FALSE}
p_beta <- ggarrange(
  tsne_bac + ggtitle("bacteria"),
  tsne_read + ggtitle("arg read"),
  tsne_contigs + ggtitle("arg contig"),
  ncol = 3, common.legend = T
)

p <- ggarrange(
  p_shannon,
  p_beta,
  p_composition,
  ncol = 1, heights = c(6,6,12)
)
```


```{r, fig.width=14, fig.height=14, warning=FALSE}
png(filename = "results.png", width = 4200, height = 4200, res = 300)
p
dev.off()
```



