---
title: "R Notebook"
---

```{r, message=FALSE}
library(tidyverse)
```

```{r}
arg_contigs <- readRDS("../data/R/arg_contigs.rds")
meta_sample <- readRDS("../data/R/meta_sample.rds")

abun_arg_contigs_gene <- arg_contigs %>%
  dplyr::select(sample_id, Gene, `RPKM coverm`) %>%
  group_by(sample_id, Gene) %>%
  summarise(abun = sum(`RPKM coverm`), .groups = "drop") %>%
  pivot_wider(names_from = "Gene", values_from = "abun", values_fill = 0) %>%
  column_to_rownames("sample_id")

abun_arg_contigs_gene <- abun_arg_contigs_gene[meta_sample$sample_id, ]

all(rownames(abun_arg_contigs_gene) == meta_sample$sample_id)
```

### MOBILE ABUNDANCE CLEAN VS DIRTY

```{r}
sample_rpkm_arg_contigs_mob <- arg_contigs %>%
  filter(integron_platon != "") %>%
  group_by(sample_id) %>%
  summarise(sample_rpkm = sum(`RPKM coverm`), .groups = "drop") %>%
  left_join(meta_sample, by = "sample_id") %>%
  dplyr::select(sample_id, sample_rpkm, Surface_Type)
```

```{r, fig.width=6.5, fig.height=4}
p <- sample_rpkm_arg_contigs_mob %>%
  ggplot(aes(x = Surface_Type, y = sample_rpkm, fill = Surface_Type)) +
  geom_boxplot() +
  theme_bw()
p
```

```{r}
png(filename = "../plots/supplementary1.png", 
    width = 6*600, height = 4*600, res = 600)
p
dev.off()
```


```{r}
wilcox.test(sample_rpkm ~ Surface_Type, 
            data = filter(sample_rpkm_arg_contigs_mob, Surface_Type != "carcass"))
```


### AMR MOBILE ABUNDANCE CLEAN VS DIRTY MOBILEOG

```{r}
arg_contigs_mobileOG <- readRDS("../data/R/arg_contigs_mobileOG.rds")
```

```{r}
sample_rpkm_arg_contigs_mobileOG <- arg_contigs %>%
  filter(Contig_name %in% unique(arg_contigs_mobileOG$contig_id)) %>%
  group_by(sample_id) %>%
  summarise(sample_rpkm = sum(`RPKM coverm`), .groups = "drop") %>%
  left_join(meta_sample, by = "sample_id") %>%
  dplyr::select(sample_id, sample_rpkm, Surface)
```

```{r, fig.width=6.5, fig.height=4}
p <- sample_rpkm_arg_contigs_mobileOG %>%
  ggplot(aes(x = Surface, y = sample_rpkm, fill = Surface)) +
  geom_boxplot(alpha = .5) +
  geom_jitter() +
  theme_bw()
p
```


```{r}
wilcox.test(sample_rpkm ~ Surface, 
            data = filter(sample_rpkm_arg_contigs_mobileOG, Surface_Type != "carcass"))
```




