---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
# read abundance matrix of resfinder gene occurence at read level
abun <- readRDS("../../data/R/counts_resfinder_reads.rds")
meta <- readRDS("../../data/R/metadata_samples_reads.rds")
```

```{r}
tibble(
  sample = rownames(abun),
  sample_depth = rowSums(abun)
) %>%
  left_join(meta %>% rownames_to_column("sample"), by = "sample") %>%
  ggplot(aes(x = sample_depth)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") +
  #scale_x_log10() +
  facet_grid(Country ~ Tecnology) +
  theme_bw()
```

```{r}
# Really strange, nanopore seems to have really low resfinder gene counts
# In two samples of nanopore completly miss AMR...
meta %>%
  rownames_to_column("sample") %>%
  mutate(sample_id = str_sub(sample, 1, -3), .after = sample) %>%
  mutate(ToT_Count = rowSums(abun)) %>%
  select(sample_id, Tecnology, ToT_Count) %>%
  pivot_wider(names_from = Tecnology, values_from = ToT_Count) %>%
  mutate(Ratio_Tot_Count = Nanopore / Illumina) %>%
  ggplot(aes(x = Ratio_Tot_Count)) +
  geom_histogram(binwidth = .01, fill = "lightblue", color = "darkblue")
```

From this evidences I'll start with AMR found in short reads obtained from Illumina only


```{r}
tibble(
  "Gene" = colnames(abun),
  "prevalence" = colSums(abun>0) / nrow(abun),
  "median_non_zero" = apply(abun, 2, \(x) median(x[x>0])),
  "RF_ToT_Counts" = colSums(abun)
) %>%
  pivot_longer(-Gene, names_to = "stat", values_to = "value") %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") +
  facet_wrap(~stat, scales = "free") +
  theme_bw() +
  theme(axis.title = element_blank())
```

```{r}
abun_filt <- abun[, colSums(abun>0) >= 10 &
                    apply(abun, 2, \(x) median(x[x>0])) >= 3]

tibble(value = rowSums(abun_filt) / rowSums(abun)) %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") +
  theme_bw() +
  xlab("preserved counts after filtering")
```

